# Generated by Django 6.0.2 on 2026-04-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_alter_itempedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ANULADO', 'Anulado')], default='INGRESADO', max_length=10, verbose_name='Estado del Pedido'),
        ),
    ]
