# Generated by Django 6.0.2 on 2026-04-05 01:33

import django.core.validators
import django.db.models.deletion
import miapp.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres.'), django.core.validators.RegexValidator(code='nombre_invalido', message='No se aceptan números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('email', models.EmailField(max_length=254, validators=[miapp.validators.validar_correo_real])),
                ('mensaje', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='El mensaje debe tener al menos 10 caracteres.')])),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres.'), django.core.validators.RegexValidator(code='nombre_invalido', message='No se aceptan números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('imagen_avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
