"""
Django settings for mi_projecto project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
from django.contrib.messages import constants as messages
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env en la raíz del proyecto
# (BASE_DIR apunta a la carpeta 'mi_projecto')
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['gatopobreteck.cl', 'www.gatopobreteck.cl',
                 'tienda-gatopobre.epsmolduras.cl', '127.0.0.1', 'localhost']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Agrega esta línea para incluir la aplicación de archivos estáticos
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'compressor',
    'debug_toolbar',
    'miapp',
    'tienda',
    'modulo_feedback',
    # para hacer limpieza de la imagen avatar al eliminar un usuario
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # <-- Nuestro middleware optimizador
    'miapp.middleware.ProfileAndGroupMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tienda.context_processors.extras_carro',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

# Se establece en False para evitar conflictos con bases de datos MySQL
# que no tienen las definiciones de zona horaria cargadas, como en muchos
# hostings compartidos. Django trabajará con fechas y horas "naives" (ingenuas).
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Directorio donde collectstatic recopilará los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- Configuración de django-compressor (Minificación) ---
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# En producción (DEBUG=False) minificará el código. En local (DEBUG=True) lo dejará legible.
COMPRESS_ENABLED = not DEBUG
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_FILTERS = {
    'css': ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter'],
    'js': ['compressor.filters.jsmin.JSMinFilter']
}

# Configuración para subir imágenes (avatares)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Sobrescribimos las etiquetas de los mensajes de Django para que calcen con Bootstrap
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# para manejar las url de autentificacion
LOGIN_URL = "miapp:login"
LOGIN_REDIRECT_URL = "miapp:dashboard"
LOGOUT_REDIRECT_URL = "miapp:inicio"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CABECERAS DE SEGURIDAD HTTP (SECURITY HEADERS) ---
# Protege contra ataques de Clickjacking (click secuestrado)
X_FRAME_OPTIONS = 'DENY'
# Evita que el navegador intente "adivinar" el tipo de contenido (MIME-sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True
# Activa el filtro XSS (Cross-Site Scripting) del navegador
SECURE_BROWSER_XSS_FILTER = True

# --- CONFIGURACIONES DINÁMICAS DE SEGURIDAD EN PRODUCCIÓN ---
if not DEBUG:
    # Obliga a que cualquier conexión HTTP se redirija a HTTPS
    SECURE_SSL_REDIRECT = True
    # Hace que las cookies de sesión y de formularios solo viajen por redes seguras
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Le dice a los navegadores que tu sitio solo debe cargarse por HTTPS
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# --- Configuración para ver las consultas SQL en la consola ---
# Solo se activará si estás en entorno de desarrollo local
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }

    # Requerido por Django Debug Toolbar para saber en qué IPs mostrar el panel
    INTERNAL_IPS = [
        '127.0.0.1',
    ]

# --- CONFIGURACIÓN DE ENVÍO DE CORREO ---
if DEBUG:
    # En desarrollo, los correos se imprimirán en la consola para pruebas.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En producción, se leen todas las credenciales desde el archivo .env
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
